version: '3.8'

services:
  postgres:
    image: postgres:17-alpine3.20
    container_name: kyoso-dev-postgres
    environment:
      POSTGRES_USER: kyoso
      POSTGRES_PASSWORD: kyoso
      POSTGRES_DB: kyoso_dev
    command: >
      sh -c '
        docker-entrypoint.sh postgres &
        until pg_isready --username "kyoso" --dbname "postgres"; do sleep 1; done;
        if [ ! -f /var/lib/postgresql/data/.test_db_initialized ]; then
          psql -v ON_ERROR_STOP=1 --username "kyoso" --dbname "postgres" -c "CREATE DATABASE \"kyoso_test\";"
          touch /var/lib/postgresql/data/.test_db_initialized;
        fi;
        wait
      '
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '3010:5432'

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: kyoso-dev-minio
    environment:
      MINIO_ROOT_USER: kyoso
      MINIO_ROOT_PASSWORD: kyoso123
    command: server /data --address :9000 --console-address :9001
    volumes:
      - minio_data:/data
    ports:
      - '3011:9000'
      - '3012:9001'

  redis:
    image: redis:7
    container_name: kyoso-dev-redis
    command: redis-server --appendonly yes --maxmemory 128mb --databases 2 --requirepass kyoso
    ports:
      - '3013:6379'
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: kyoso-dev-meilisearch
    command: meilisearch --master-key rhwMvpQ6ZZqBTtDD_OwDi9N4Kui_r1agM_Aw5-v28lo
    volumes:
      - meilisearch_data:/data
    ports:
      - '7700:7700'

volumes:
  postgres_data:
  minio_data:
  redis_data:
  meilisearch_data:
